Create security group

diff --git a/ec2-backup b/ec2-backup
--- a/ec2-backup
+++ b/ec2-backup
@@ -8,10 +8,16 @@ PATH=$(command -p getconf PATH)
 
 USAGE="usage: $(basename "$0") [-h] [-l filter] [-r filter] [-v volume-id] dir"
 VOLUME=""
-LOCAL_FILTER="cat"
-REMOTE_FILTER="cat"
+LOCAL_FILTER="cat -"
+REMOTE_FILTER="cat -"
 DIR=""
 AVAILABILITY_ZONE=""
+EC2_AMI="ami-7ad76705"
+
+# Security group configuration
+SG_NAME="ec2-backup"
+SG_DESC="Temporary security group for ec2-backup"
+SG_ID=""
 
 usage () {
     echo "$USAGE"
@@ -62,10 +68,12 @@ validate_volume () {
         echoerr "Invalid volume ID"
         exit 1
     fi
+
     if [ "$VOLUME_SIZE" -lt "$SIZE" ]; then
         echoerr "Volume must be at least $SIZE GB"
         exit 1
     fi
+
     if [ "$STATE" != "available" ]; then
         echoerr "Volume is unavailable"
         exit 1
@@ -74,6 +82,19 @@ validate_volume () {
 
 debug_print () {
     [ -z "$EC2_BACKUP_VERBOSE" ] || echo "$1"
+}
+
+create_security_group () {
+    debug_print "Creating security group"
+    SG_ID=$(aws ec2 create-security-group --description "$SG_DESC" --group-name "$SG_NAME" 2>&1)
+
+    if echo "$SG_ID" | grep -q "error"; then
+        echoerr "Security group $SG_NAME already exists."
+        echoerr "Please delete this group, or specify a security group with '--security-groups' or '--security-group-ids'"
+        exit 1
+    fi
+
+    aws ec2 authorize-security-group-ingress --group-id "$SG_ID" --port 22 --protocol tcp --cidr 0.0.0.0/0
 }
 
 echoerr () {
@@ -97,9 +118,12 @@ main () {
         validate_volume "$VOLUME"
     fi
 
+    # TODO: Don't create if user gave us the flag
+    create_security_group
+
     debug_print "Starting EC2 instance"
-    PARAMETERS="--output text --instance-type t2.micro --image-id ami-7ad76705\
-        --placement AvailabilityZone=$AVAILABILITY_ZONE"
+    PARAMETERS="--output text --instance-type t2.micro --image-id $EC2_AMI\
+        --placement AvailabilityZone=$AVAILABILITY_ZONE --security-group-ids $SG_ID"
     INSTANCE_ID=$(aws ec2 run-instances "$PARAMETERS" \
         | awk 'FNR == 2 { print $7 }')
 
@@ -128,7 +152,7 @@ main () {
     INSTANCE_IP=$(aws ec2 describe-instances --output text --instance-ids \
         "$INSTANCE_ID" --query \
         'Reservations[*].Instances[*].{Address:PublicDnsName}')
-    tar cf - "$DIR" | "$LOCAL_FILTER" | ssh "$INSTANCE_IP" \
+    tar cf - "$DIR" | eval "$LOCAL_FILTER" | ssh "$INSTANCE_IP" \
         "$REMOTE_FILTER | dd of=\"$DEVICE\""
 
     if [ "$?" -ne 0 ]; then
