Remove 'command -p' in favor of sanitizing PATH
The previous solution of placing `command -p` in front of every
executable became cumbersome and messy. This fixes that by removing them
in favor of directly sanitizing the PATH variable in the script.

This uses getconf(1) to set a default PATH inside the script, rather
than relying on an external PATH variable. Now we can portably call
executables by just using their names without having to worry about
malicious PATH variable attacks, which makes the source a lot more
readable.

diff --git a/ec2-backup b/ec2-backup
--- a/ec2-backup
+++ b/ec2-backup
@@ -3,6 +3,9 @@
 # Jason Ajmo and Bradford Smith
 # CS 615 HW6 ec2-backup
 
+# sanitize PATH variable
+PATH=$(command -p getconf PATH)
+
 USAGE="usage: $0 [-h] [-l filter] [-r filter] [-v volume-id] dir"
 VOLUME=""
 LOCAL_FILTER=""
@@ -10,12 +13,12 @@ REMOTE_FILTER=""
 DIR=""
 
 usage () {
-    command -p echo "$USAGE"
+    echo "$USAGE"
     exit 1
 }
 
 help_message () {
-    command -p echo "$USAGE"
+    echo "$USAGE"
     cat<<EOF
  -h             Print this help message.
  -l filter      Pass data through the given filter command on the local host
@@ -45,29 +48,29 @@ parse_input () {
 
 echoerr () {
     # same as 'echo' but print to STDERR
-    1>&2 command -p echo "$@"
+    1>&2 echo "$@"
 }
 
 main () {
     parse_input "$@"
-    SIZE=$(command -p du -gs "$DIR" 2> /dev/null | command -p awk '{ print $1 * 2 }')
+    SIZE=$(du -gs "$DIR" 2> /dev/null | awk '{ print $1 * 2 }')
 
     if [ -z "$VOLUME" ]; then
-        AVAILABILITY_ZONE=$(command -p aws ec2 describe-availability-zones --output text | command -p sed '1q;d' | command -p awk '{ print $4 }')
-        OUTPUT=$(command -p aws ec2 create-volume --output text --availability-zone "$AVAILABILITY_ZONE" --size "$SIZE")
-        VOLUME=$(command -p echo "$OUTPUT" | command -p awk '{ print $6 }')
+        AVAILABILITY_ZONE=$(aws ec2 describe-availability-zones --output text | sed '1q;d' | awk '{ print $4 }')
+        OUTPUT=$(aws ec2 create-volume --output text --availability-zone "$AVAILABILITY_ZONE" --size "$SIZE")
+        VOLUME=$(echo "$OUTPUT" | awk '{ print $6 }')
     else
-        VOLUME_INFO=$(command -p aws ec2 describe-volumes --output text --volume-ids "$VOLUME" --query 'Volumes[*].{Size:Size,AvailabilityZone:AvailabilityZone,State:State}' 2>&1)
-        VOLUME_SIZE=$(command -p echo "$VOLUME_INFO" | command -p awk '{ print $2 }')
-        command -p echo "$VOLUME_SIZE" | command -p grep -q "error" && { echoerr "Invalid volume ID"; exit 1; }
-        STATE=$(command -p echo "$VOLUME_INFO" | command -p awk '{ print $3 }')
-        AVAILABILITY_ZONE=$(command -p echo "$VOLUME_INFO" | command -p awk '{ print $1 }')
+        VOLUME_INFO=$(aws ec2 describe-volumes --output text --volume-ids "$VOLUME" --query 'Volumes[*].{Size:Size,AvailabilityZone:AvailabilityZone,State:State}' 2>&1)
+        VOLUME_SIZE=$(echo "$VOLUME_INFO" | awk '{ print $2 }')
+        echo "$VOLUME_SIZE" | grep -q "error" && { echoerr "Invalid volume ID"; exit 1; }
+        STATE=$(echo "$VOLUME_INFO" | awk '{ print $3 }')
+        AVAILABILITY_ZONE=$(echo "$VOLUME_INFO" | awk '{ print $1 }')
         [ "$VOLUME_SIZE" -lt "$SIZE" ] && { echoerr "Volume must be at least $SIZE GB"; exit 1; }
         [ "$STATE" != "available" ] && { echoerr "Volume is unavailable"; exit 1; }
         exit 0
     fi
 
-    INSTANCE_ID=$(command -p aws ec2 run-instances --output text --instance-type t2.micro --image-id ami-7ad76705 --placement AvailabilityZone="$AVAILABILITY_ZONE" | command -p awk 'FNR == 2 { print $7 }')
+    INSTANCE_ID=$(aws ec2 run-instances --output text --instance-type t2.micro --image-id ami-7ad76705 --placement AvailabilityZone="$AVAILABILITY_ZONE" | awk 'FNR == 2 { print $7 }')
 
     echo "$INSTANCE_ID"
 }
