Add sanity checks to volume usage

diff --git a/ec2-backup b/ec2-backup
--- a/ec2-backup
+++ b/ec2-backup
@@ -51,15 +51,26 @@ echoerr () {
 
 main () {
     parse_input "$@"
+	SIZE=$(/usr/bin/du -gs "$DIR" 2> /dev/null | /usr/bin/awk '{ print $1 * 2 }')
 
     if [ "$VOLUME" = "" ]; then
-		SIZE=$(/usr/bin/du -gs "$DIR" 2> /dev/null | /usr/bin/awk '{ print $1 * 2 }')
+		AVAILABILITY_ZONE="$REGION"
 		OUTPUT=$(/usr/pkg/bin/aws ec2 create-volume --output text --availability-zone "$REGION" --size "$SIZE")
 		VOLUME=$(/bin/echo "$OUTPUT" | /usr/bin/awk '{ print $6 }')
-    fi
+    else
+		VOLUME_INFO=$(/usr/pkg/bin/aws ec2 describe-volumes --output text --volume-ids "$VOLUME" --query 'Volumes[*].{Size:Size,AvailabilityZone:AvailabilityZone,State:State}' 2>&1)
+		[ "$(/bin/echo "$VOLUME_SIZE" | /usr/bin/grep "error")" != "" ] && { echoerr "Invalid volume ID"; exit 1; }
+		VOLUME_SIZE=$(/bin/echo "$VOLUME_INFO" | /usr/bin/awk '{ print $2 }')
+		STATE=$(/bin/echo "$VOLUME_INFO" | /usr/bin/awk '{ print $3 }')
+		AVAILABILITY_ZONE=$(/bin/echo "$VOLUME_INFO" | /usr/bin/awk '{ print $1 }')
+		[ "$VOLUME_SIZE" -lt $SIZE ] && { echoerr "Volume must be at least $SIZE GB"; exit 1; }
+		[ "$STATE" != "available" ] && { echoerr "Volume is unavailable"; exit 1; }
+		exit 0
+	fi
 
-    # TODO: everything
+	INSTANCE_ID=$(/usr/pkg/bin/aws ec2 run-instances --output text --instance-type t2.micro --image-id ami-7ad76705 --placement AvailabilityZone="$AVAILABILITY_ZONE" | /usr/bin/awk 'FNR == 2 { print $7 '})
+
+	echo "$INSTANCE_ID"
 }
 
-# call main function
 main "$@"
